### PR TITLE
MT942 compatibility / Year boundary compatibility

### PR DESCRIPTION
**Pull request by kangguru**
- when parsing statements end/start of the year we've mixed up some years
- when parsing MT942 statements the generation date is stored in field 13

### CODE REVIEW

**Comment by bumi** [comment]
nice! 👍 
for mt942 compatibility still more is needed, isn't it? isse: #12

**Comment by grncdr** [comment]
This resolved the year boundary issue for the cases we had as well 👍 . Can/will this be merged before the rest of the issues mentioned in #12?

**Comment by kangguru** [comment]
haha, i even wasn't aware that there is a MT942 issue 😇 shame on me

**Comment by kangguru** [comment]
@grncdr new release just hit the road, happy parsing!

**Pull request merged**
