### PR TITLE
allow defining parsers for non-digit tags

### PR DESCRIPTION
**Pull request by prometh07**

### CODE REVIEW

**Comment by bumi** [comment]
@Uepsilon what do you think? 
for me this looks like a safe change. maybe we can add some specs for that parser?

**Comment by bumi** [comment]
which would probably be a spec to parse an example of such an MT940 file?

**Comment by bumi** [comment]
@Uepsilon did you merge it now without specs?!

**Comment by Uepsilon** [comment]
I did and added a spec afterwards.

**Comment by bumi** [comment]
ah, missed that. great! :tada:

**Comment by Uepsilon** [comment]
i wasn't sure if i could have appended my specs to the PR of @prometh07 as it was coming from his fork. is that possible or what would have been the way to go here?

**Comment by bumi** [comment]
yep, pushing in the branch and thus updating the PR would be best I guess.

**Comment by Uepsilon** [comment]
but i could not have pushed in that branch as it came from a fork i do not have write access to

**Comment by Uepsilon** [comment]
could have mirrored the branch and then updated the PR

**Comment by prometh07** [comment]
I was going to add some specs but you guys were faster. ;)

**Comment by Uepsilon** [comment]
⚡️ 🏎 🏃 💨 

:)

**Comment by bumi** [comment]
@Uepsilon typically (by default) it is enabled that maintainers have write access to the branch of the fork to update the PR. 
So you could have pushed to `prometh07:nonswift_fields` and this PR would have been updated. 
This is probably also a best practice as everything related to this PR is then documented here.

**Comment by Uepsilon** [comment]
ah. this is amazing to know. i was not aware of that.. thanks @bumi, i'll check it next time

**Pull request merged**
