### PR TITLE
fix parsing of sepa information

### PR DESCRIPTION
**Pull request by kangguru**
If the information field contains sepa information but one of the keys doesn't hold
a value, the parser will break like we've seen in e6b2c66743b8d5cbc7d2c80f8a3cdc2ab5eb0011 

Therefore we don't reject empty values from the parsed result anymore.

### CODE REVIEW

**Comment by bumi** [comment]
ah, darüber hatten wir schon mal gesprochen, oder?

**Comment by bumi** [comment]
any idea why travis fails while installing it?

**Comment by kangguru** [comment]
we had something similar before.

re: travis, nah... but it should work now (moved to the container infrastructure)

**Comment by bumi** [comment]
\o/

**Pull request merged**
